name: nb_maps_flutter
description: A Flutter plugin for integrating Nextbillion's Maps SDK to your Flutter Project.
version: 0.4.1
homepage: https://github.com/nextbillion-ai/nb-maps-flutter

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.nextbillion.maps_flutter
        pluginClass: NbMapsPlugin
      ios:
        pluginClass: SwiftNbMapsFlutterPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=2.0.0"
