name: nb_maps_flutter
description: A Flutter plugin for integrating Nextbillion's Maps SDK to your Flutter Project.
version: 0.4.1
homepage: https://github.com/nextbillion-ai/nb-maps-flutter

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.nextbillion.maps_flutter
        pluginClass: NbMapsPlugin
      ios:
        pluginClass: SwiftNbMapsFlutterPlugin

environment:  
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"
